// client/src/game/components/GameHand.tsx
import { useMemo } from 'react'
import type { Hand, Player } from '../types'
import { useGameStore } from '../store'
import HandTotal from './HandTotal'
import HandBet from './HandBet'
import PlayingCard from './PlayingCard'

type GameHandProps = {
  hand: Hand
  player: Player
}

const GameHand = ({ hand, player }: GameHandProps) => {
  const activeHand = useGameStore((state) => state.activeHand)
  const activePlayer = useGameStore((state) => state.activePlayer)
  const showDealerHoleCard = useGameStore((state) => state.showDealerHoleCard)
  const isDealer = player.isDealer

  const isActiveHand = activeHand === hand && !player.isDealer
  const isSplitHand = useMemo(
    () => activePlayer === player && !!activeHand && player.hands.length > 1,
    [activeHand, activePlayer, player],
  )

  const isFaceDown = (cardIndex: number) => isDealer && cardIndex === 1 && !showDealerHoleCard

  const isSplitCard = (card: Card) => {
    if (player.hands.indexOf(hand) !== 1) return false
    return hand.cards.indexOf(card) === 0
  }

  return (
    <article className={`hand ${isActiveHand ? 'active-hand' : ''} ${isSplitHand ? 'split-hand' : ''}`}>
      <h2 className="sr-only">{isDealer ? "Dealer's" : 'Your'} hand</h2>
      {hand.cards.map((card, index) => (
        <PlayingCard
          key={`${hand.id}-${card.index}`}
          card={card}
          isFaceDown={isFaceDown(index)}
          className={isSplitCard(card) ? 'split-card' : ''}
        />
      ))}
      <HandBet hand={hand} />
      {!player.isDealer && (
        <div className="hand-result">
          {hand.result && (
            <svg className={hand.result === 'blackjack' ? 'blackjack' : ''}>
              <use href={`#result-${hand.result}`} />
            </svg>
          )}
        </div>
      )}
      <HandTotal hand={hand} isDealer={isDealer} />
    </article>
  )
}

export default GameHand

// client/src/vue-game/components/GameHand.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Card, Hand, Player } from '../../game/types'
import HandTotal from './HandTotal.vue'
import HandBet from './HandBet.vue'
import PlayingCard from './PlayingCard.vue'

const props = defineProps<{
  hand: Hand
  player: Player
  activeHand: Hand | null
  activePlayer: Player | null
  showDealerHoleCard: boolean
}>()

const isActiveHand = computed(() => props.activeHand === props.hand && !props.player.isDealer)
const isSplitHand = computed(
  () => props.activePlayer === props.player && !!props.activeHand && props.player.hands.length > 1,
)
const isDealer = computed(() => props.player.isDealer)

const isFaceDown = (cardIndex: number) =>
  isDealer.value && cardIndex === 1 && !props.showDealerHoleCard

const isSplitCard = (card: Card) => {
  if (props.player.hands.indexOf(props.hand) !== 1) return false
  return props.hand.cards.indexOf(card) === 0
}
</script>

<template>
  <article class="hand" :class="{ 'active-hand': isActiveHand, 'split-hand': isSplitHand }">
    <TransitionGroup name="deal-card" tag="div" class="hand-cards">
      <PlayingCard
        v-for="(card, index) in hand.cards"
        :key="`${hand.id}-${card.index}`"
        :card="card"
        :is-face-down="isFaceDown(index)"
        :class="{ 'split-card': isSplitCard(card) }"
        :style="{ '--index': index }"
      />
    </TransitionGroup>
    <HandBet :hand="hand" />
    <div v-if="!player.isDealer" class="hand-result">
      <svg v-if="hand.result" :class="{ blackjack: hand.result === 'blackjack' }">
        <use :href="`#result-${hand.result}`" />
      </svg>
    </div>
    <HandTotal :hand="hand" :is-dealer="player.isDealer" :show-dealer-hole-card="showDealerHoleCard" />
  </article>
</template>
