// client/src/game/components/PlayerToolbar.tsx
import { useMemo } from 'react'
import { useGameStore } from '../store'
import { useAuthStore } from '../../store/authStore'
import PlayerBank from './PlayerBank'

const PlayerToolbar = () => {
  const isDealing = useGameStore((state) => state.isDealing)
  const activePlayer = useGameStore((state) => state.activePlayer)
  const activeHand = useGameStore((state) => state.activeHand)
  const doubleDown = useGameStore((state) => state.doubleDown)
  const split = useGameStore((state) => state.split)
  const endHand = useGameStore((state) => state.endHand)
  const hit = useGameStore((state) => state.hit)
  const isActionPending = useGameStore((state) => state.isActionPending)
  const userId = useAuthStore((state) => state.user?.id)

  const isMyTurn = !activePlayer?.userId || activePlayer.userId === userId

  const canDoubleDown = useMemo(() => {
    if (isDealing) return false
    if (!activePlayer || !activeHand) return false
    if (activePlayer.bank < activeHand.bet) return false
    return activeHand.cards.length === 2 && activePlayer.hands.length === 1
  }, [activeHand, activePlayer, isDealing])

  const canSplit = useMemo(() => {
    if (isDealing) return false
    if (!activePlayer || !activeHand) return false
    if (activePlayer.bank < activeHand.bet) return false
    return (
      activeHand.cards.length === 2 &&
      activePlayer.hands.length === 1 &&
      activeHand.cards[0].rank === activeHand.cards[1].rank
    )
  }, [activeHand, activePlayer, isDealing])

  return (
    <div className="player-toolbar" role="toolbar">
      <button
        disabled={!canDoubleDown || !isMyTurn || isActionPending}
        onClick={() => void doubleDown()}
      >
        Double<br />Down
      </button>
      <button disabled={!canSplit || !isMyTurn || isActionPending} onClick={() => void split()}>
        Split
      </button>
      <PlayerBank />
      <button disabled={isDealing || !isMyTurn || isActionPending} onClick={() => void endHand()}>
        Stand
      </button>
      <button disabled={isDealing || !isMyTurn || isActionPending} onClick={() => void hit()}>
        Hit
      </button>
    </div>
  )
}

export default PlayerToolbar

// client/src/vue-game/components/PlayerToolbar.vue
<script setup lang="ts">
import PlayerBank from './PlayerBank.vue'

const props = defineProps<{
  bank: number
  canDoubleDown: boolean
  canSplit: boolean
  isDealing: boolean
  isActionPending: boolean
  isMyTurn: boolean
  onDoubleDown?: () => void
  onSplit?: () => void
  onStand?: () => void
  onHit?: () => void
}>()
</script>

<template>
  <div class="player-toolbar" role="toolbar">
    <button
      :disabled="!canDoubleDown || !isMyTurn || isActionPending"
      @click="props.onDoubleDown && props.onDoubleDown()"
    >
      Double<br />Down
    </button>
    <button
      :disabled="!canSplit || !isMyTurn || isActionPending"
      @click="props.onSplit && props.onSplit()"
    >
      Split
    </button>
    <PlayerBank :bank="props.bank" />
    <button
      :disabled="isDealing || !isMyTurn || isActionPending"
      @click="props.onStand && props.onStand()"
    >
      Stand
    </button>
    <button
      :disabled="isDealing || !isMyTurn || isActionPending"
      @click="props.onHit && props.onHit()"
    >
      Hit
    </button>
  </div>
</template>
