// client/src/vue-game/components/HandBet.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Hand } from '../../game/types'

const props = defineProps<{ hand: Hand }>()
const chipCount = computed(() => Math.min(props.hand.bet, 10))
const isLoss = computed(() => ['lose', 'bust'].includes(props.hand.result ?? ''))
const isWin = computed(() => ['push', 'win', 'blackjack'].includes(props.hand.result ?? ''))
</script>

<template>
  <div class="hand-bet" :class="{ 'is-win': isWin, 'is-loss': isLoss }">
    <svg v-for="i in chipCount" :key="i" class="chip">
      <use href="#chip" />
    </svg>
  </div>
</template>

// client/src/game/components/HandBet.tsx
import type { Hand } from '../types'

const MAX_VISIBLE_CHIPS = 6

const HandBet = ({ hand }: { hand: Hand }) => {
  const isLoss = hand.result ? ['lose', 'bust'].includes(hand.result) : false
  const isWin = hand.result ? ['push', 'win', 'blackjack'].includes(hand.result) : false
  const chipCount = Math.max(hand.bet, 0)
  const visibleChips = Math.min(chipCount, MAX_VISIBLE_CHIPS)

  return (
    <div className={`hand-bet ${isWin ? 'is-win' : ''} ${isLoss ? 'is-loss' : ''}`}>
      {Array.from({ length: visibleChips }, (_, i) => (
        <svg className="chip" key={`${hand.id}-${i}`}>
          <use href="#chip" />
        </svg>
      ))}
      {chipCount > MAX_VISIBLE_CHIPS && (
        <span className="chip-count">x{chipCount}</span>
      )}
    </div>
  )
}

export default HandBet
