// client/src/vue-game/components/HandTotal.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Hand } from '../../game/types'

const props = defineProps<{ hand: Hand; isDealer: boolean; showDealerHoleCard: boolean }>()

const total = computed(() => {
  if (props.hand.cards.length === 0) return null
  if (props.isDealer && !props.showDealerHoleCard) return null
  return props.hand.total
})
</script>

<template>
  <p v-if="total !== null" class="hand-total" :class="{ bust: total > 21, 'twenty-one': total === 21 }">
    <span class="sr-only">Total:</span>
    {{ total }}
  </p>
</template>

// client/src/game/components/HandTotal.tsx
import { useMemo } from 'react'
import { useGameStore } from '../store'
import type { Hand } from '../types'

const HandTotal = ({ hand, isDealer }: { hand: Hand; isDealer: boolean }) => {
  const showDealerHoleCard = useGameStore((state) => state.showDealerHoleCard)

  const total = useMemo(() => {
    if (hand.cards.length < 2) return null
    if (isDealer && !showDealerHoleCard) return null
    return hand.total
  }, [hand, isDealer, showDealerHoleCard])

  if (!total) return null

  return (
    <p className={`hand-total ${total > 21 ? 'bust' : ''} ${total === 21 ? 'twenty-one' : ''}`}>
      <span className="sr-only">Total:</span>
      {total}
    </p>
  )
}

export default HandTotal
