// client/src/vue-game/components/PlayerBank.vue
<script setup lang="ts">
const props = defineProps<{ bank: number }>()
</script>

<template>
  <span role="status" class="bank">
    <svg role="img" aria-label="Chips" class="chip">
      <use href="#chip" />
    </svg>
    <span class="times">&times;</span>
    <span class="number">{{ props.bank }}</span>
  </span>
</template>

// client/src/game/components/PlayerBank.tsx
import { useEffect, useRef, useState } from 'react'
import { useGameStore } from '../store'

const PlayerBank = () => {
  const bank = useGameStore((state) => state.players[0].bank)
  const previous = useRef(bank)
  const [isIncreasing, setIsIncreasing] = useState(false)

  useEffect(() => {
    if (bank > previous.current) {
      setIsIncreasing(true)
      const timeout = window.setTimeout(() => setIsIncreasing(false), 1000)
      previous.current = bank
      return () => window.clearTimeout(timeout)
    }
    previous.current = bank
  }, [bank])

  return (
    <span role="status" className={`bank ${isIncreasing ? 'is-increasing' : ''}`}>
      <svg role="img" aria-label="Chips" className={`chip ${isIncreasing ? 'is-spinning' : ''}`}>
        <use href="#chip" />
      </svg>
      <span className="times">&times;</span>
      <span className="number">{bank}</span>
    </span>
  )
}

export default PlayerBank
